[package]
name = "fieldmask"
version = "0.1.0"
authors = ["Weiwei Lin <weiwei.will.lin@gmail.com>"]
edition = "2018"

[dependencies]
derive_more = "0.99.11"
fieldmask_derive = { path = "../fieldmask_derive" }
thiserror = "1.0.22"
